### PR TITLE
Enhancements for introspection and debugging

### PR DESCRIPTION
**Pull request by ngjunsiang**
## Problem

While trying to test this package, I found that it was tedious to initialise classes from `dis7` as the `__init__()` takes no arguments. That means PDUs and other objects must be instantiated first, then their attributes set one by one (or parsed from a stream).

I also saw the same complaint in #12 and thought this might be a useful enhancement.

## Solution

A typical design for data classes is for the attribute values to be taken from the `__init__()` parameters, so that objects can be initialised in one line. This can be implemented without breaking any of the tests or existing code, by giving the parameters default values.

This PR shows the proposed change on three classes: DataQueryDatumSpecification, FixedDatum, and VariableDatum. I'd like to gauge interest (and any objections) in this feature first before I proceed to apply the same pattern to the remaining classes.

## After PR

    ~/open-dis-python$ python
    Python 3.10.11 (main, Apr  4 2023, 22:10:32) [GCC 12.2.0] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> from opendis.dis7 import DataQueryDatumSpecification
    >>> dqds = DataQueryDatumSpecification(numberOfFixedDatums=1, numberOfVariableDatums=2)
    >>> dqds.fixedDatumIDList
    []

### CODE REVIEW

**Comment by leif81** [comment]
The proposal makes sense to me @ngjunsiang .

I'll leave the PR open for a week to collect any other feedback . If there are no concerns raised as a comment here I'll go ahead and merge.

**Comment by ngjunsiang** [comment]
While this PR is still open, I have a couple of questions from going through the code in more detail as I add the init parameters:

https://github.com/open-dis/open-dis-python/blob/71c34b0ba6de90985a85e37c59f0107d9913463b/opendis/dis7.py#L654-L665
I see a few *Chunk classes in dis7.py but don't see them being used anywhere. What are these used for?

https://github.com/open-dis/open-dis-python/blob/71c34b0ba6de90985a85e37c59f0107d9913463b/opendis/dis7.py#L329-L346
I see in many classes that the padding is stored as an object attribute, although its value is always 0. This seems unnecessary when the padding can be added during serialization and ignored during parsing; is there a reason the padding value is kept?

**Comment by leif81** [comment]
The use of Chunk was intended to be refactored out but some occurences may have been missed. A pull request to remove any remaining is welcome.

**Comment by leif81** [comment]
@ngjunsiang About the padding, I don't know what it's like that, it's likely a relic of the old code generator. Feel free to refactor that out too in a pull request.

**Comment by leif81** [comment]
@ngjunsiang I remember now about the padding. It's there to be explicit and consistent with the spec. It's a field of particular size. Suggest we leave the padding as is.

**Comment by ngjunsiang** [comment]
## `__init__()`
Okay, I've added `__init__()` parameters for almost all the Record and PDU classes. I have kept the `padding` attributes, though they are not included in the inits; that introduces the chance of a user setting a value to padding instead of another attribute.

## Attribute renaming

The following attributes have undergone slight renaming for consistency (there were multiple slightly different names for them scattered throughout the code):

- numberOfFixedDatums
- numberOfVariableDatums
- fixedDatumIDs
- variableDatumIDs
- numberOfFixedDatumRecords
- numberOfVariableDatumRecords
- fixedDatumRecords
- variableDatumRecords

## Removed *Chunk classes

Removed the *Chunk classes as requested.

**Comment by ngjunsiang** [comment]
## Further proposed changes

I have a few other edits I'd like to make separately, after this merge, since they might change the implementation somewhat (even if I try to preserve the existing interface):

### Use composition for `DataQueryDatumSpecification` and `DatumSpecification`

There are a number of PDUs that encapsulate datums. A quick count:
- Data Query PDU
- Action Request PDU
- Data PDU
- Set Data PDU
- Event Report PDU
- Comment PDU
- ... and their Reliable counterparts

These classes reimplement the attributes and serialization/parse methods, where composition could be used instead. The attributes can still be made available through the use of [Python's `property`](https://docs.python.org/3/library/functions.html#property). This would reduce the amount of code to maintain and synchronise.

I have already spotted at least one bug where a `DataQueryDatumSpecification` is used instead of a `DatumSpecification`; this composition pattern would help make such occurrences easier to spot, and less work to fix.

### Improved implementation for `DataQueryDatumSpecification` and `DatumSpecification`

These currently require the user to know upfront the number of datums, which is potentially fragile. The datum count is easily calculated using `len()` and this can be done automatically during serialization, or used for validation during parsing.

In `parse()` datums also should not be appended to the existing list of datums, since this will lead to an inaccurate count if reusing a PDU instance (is this usage pattern encouraged?) I plan to submit a bugfix after this merge.

### Type annotations

I will also begin the work of adding type annotations, to enable the use of linters and static checkers for those who use them.

**Review by ricklentz — APPROVED** [review]

**Review by leif81 — APPROVED** [review]

**Pull request merged**
