### PR TITLE
Issue #25, xmlpg generated Python working, import fix vs pip install

### PR DESCRIPTION
**Pull request by ricklentz**
This PR adds the enhancement requested in issue 25
It changes the name of DIS class reference to pythonDis.py (directly using Python generated xmlpg - now working)
Removed the need to pip install (imports add relative path)

### CODE REVIEW

**Comment by leif81** [comment]
Thank-you for the PR @ricklentz 

Could you describe the PR in more detail, I'm not understanding the change right now.Thanks

**Comment by ricklentz** [comment]
The PR implements issue #25 with a minor change to the examples
It changes the name of the DIS file generated by the open-dis/xmlpg process to match that output (and thus the references)
It allows running the examples without doing a 'pip install .' (and hopefully enables easier setup for pypi package next - pending @brutzman's guidance)

**Comment by leif81** [comment]
Thanks @ricklentz . The fix for #25 is good. Thank-you. 
The other parts, maybe it would help to understand what you're trying to do. Xmlpg hasn't been used in years and the code has deviated from what's generated. Are you using it with any luck?

**Comment by leif81** [comment]
I meant to mention, since others are using this project, if you'd like to attempt to align it with Xmlpg, first of all good luck(hah! Jk), I would suggest instead proposing the change to the output filename on the Xmlpg side instead.

**Comment by leif81** [comment]
The rest of the change looks good to me, it's just the renaming of the .py file I think we should info and do that on the Xmlpg side instead.

**Comment by ricklentz** [comment]
Don asked me to look at xmlpg, and I got it to generate the Python classes using the Maven shell script in just a few minutes.  It outputs all the PDU classes into a single pythonDis.py file (without the version name).  I tested it with the EntityState sender/receiver examples in open-dis-python and another open-source air traffic project without issue.

The DIS python class file name was changed to match xmlpg (pythonDis.py vs. dis7.py) as it seems desirable over having to update the import package names each time DIS bumps up a version.

I'm not sure of the best project deployment pattern, but PyPI seems preferable over 'pip install .'  I hope these changes are constructive and helpful.  If not, or you don't agree - no worries.  Just reject, and I'll resubmit with the one-line change for #25

**Comment by leif81** [comment]
Thanks for the added context for the change @ricklentz . 

Yes in future it would help to separate the PR's into separate logical changes. It can speed up the merge process when changes are small and locally separated. For example the fix for #25 is great and I will merge that in right away if you can submit a new PR for it. Whereas other parts of PR that I still have concerns with. I want to explain the concerns a bit more now I'm in front of my keyboard and not just my phone UI.

xmlpg was originally heavily used to generate the initial code bases here for open-dis python, java, cpp, and csharp languages. Don likely mentioned that. It was a very a terrific tool to do 80% of the job to generate the PDU code. In the early days while xmlpg was being developed the open-dis code bases were regenerated repeatedly with xmlpg and each time blindly overwrote the entire open-dis code languages. This worked well at the time. Fast forward 5+ years and we've been working on the remaining 20% of the implementation corner cases that were very difficult to have xmlpg do. This 20% of the implementation were done with individual pull requests by the community, and in many cases are still being received today as new issues are found. This is a challenge, typically if there's a problem with one of the languages (e.g. open-dis-python) the same gap exists in the other langauge implementations. It's a big challenge but one that Don McGregor and I at the time felt xmlpg wasn't up to doing so we accepted individual fixes. IMO this is still the best course right now.

So all that to say, I don't want to discourage exploring and experimentally running xmlpg, but just a caution that what it generates will have huge deltas with the open-dis langauge code bases in github today. If you or someone is interested in the challenge of backporting indivdiual fixes in the open-dis repositories into xmlpg that would absolutely be interesting work, and I'd encourage trying that. But just a gentle caution that the whole reason that wasn't done years ago was because of the difficulty we felt it was. 

Hopefully this adds context as to why I don't think we should merge in `pythonDis.py` that came from xmlpg. It would not include years of fixes and those would be lost if we merged it.

Long story, yes I agree with suggestion that we should close this PR and if you can submit a PR for #25 I'll merge that one right away. I hope this doesn't discouarge you but just provides context for the size of the challenge if you're interested in helping it's welcome!

**Comment by brutzman** [comment]
Leif thanks for the great discussion and constructive guidance.  Our intent is minimal changes to existing open-dis-python codebase, simply recording and contributing refinements that appear useful.

Rick and I are currently working on a complete update to the python autogeneration as part of [open-dis7-source-generator](https://github.com/open-dis/open-dis7-source-generator) project.  We will first strive for alignment and completeness (all 72 PDUS and all enumerations, just like [open-dis7-java](https://github.com/open-dis/open-dis7-java) project.

Happy to have a meeting about all this with you and group if you like.  Thanks for considering the possibilities.

**Comment by ricklentz** [comment]
Going to resubmit per the above.

**Comment by leif81** [comment]
@brutzman yes certainly, let's do a video call sometime soon to catch up. My Gmail address is the best way to reach me outside of GitHub.

**Comment by brutzman** [comment]
Hi Leif.  I do not have your gmail address - it would be good to talk this week if possible.  Yes we have xmlpg working to good effect in open-dis7-source generator project, fully for Java and today for Python.  Recommended changes in the code design will be welcome.

**Pull request closed without merging**
