### PR TITLE
Cleanup open-dis-python.

### PR DESCRIPTION
**Pull request by savagesmc**
Hi there.  I came across your library while I was working on some software for an internal IR&D project at work, and liked how much you had done.  Our development environment is python3 inside of docker containers, so I really wanted this library to be python3 compatible, and also for it to be 'installable' via setuptools.  Also, I wanted it to be able to decode the entire library of PDUs (that you autogenerated), so I fixed that as well.

A summary of my changes were:
- Move/modify setup.py to allow installation as a full package.
- Updates to make python3 compatible.
- Fix dis7 and PduFactory to allow decoding of all types of PDUs.
- Minor fixes after running the tests.
- Update documentation.

If you like these changes, please merge this pull request into your master, and then my project can go to using your official github instead of my fork.

Thanks,

Steve

### CODE REVIEW

**Comment by savagesmc** [comment]
Also, I think this pull request addresses the two outstanding issues.

**Comment by leif81** [comment]
@savagesmc Thank you for this. I'll admit I'm not a python expert so I'm not a good judge of code quality or correctness. But all the changes seem reasonable and nothing stands out as concerning to me.

I won't click merge right away, I'll give others a chance to comment. If there are no comments in the next week I'll just go ahead and merge at that time.

**Comment by savagesmc** [comment]
Thanks!  And thanks for this open-dis project.  It saved us a lot of work.
I especially like how this project uses one common definition of the dis
standard and auto generates each languages implementation.  We doing
similar types of things at our company to speed up development and allow
language flexibility.

Thanks again!

Steve

**Comment by leif81** [comment]
@savagesmc Anymore commits coming? I'm hovering over the merge button.

**Comment by savagesmc** [comment]
Go for it!  Thanks!

**Comment by leif81** [comment]
@savagesmc do you think issues #1 and #2 should be closed now?

**Comment by savagesmc** [comment]
Yes, I believe I fixed both of those issues with pull request for #3.
Thanks!

**Pull request merged**
